sudo: required
services:
  - docker

before_install:
  - docker build -t giakoumis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run giakoumis/react-test npm test -- --coverage

after_success:
  - docker build -t giakoumis/multi-client ./client
  - docker build -t giakoumis/multi-nginx ./ngxix
  - docker build -t giakoumis/multi-server ./server
  - docker build -t giakoumis/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push giakoumis/multi-client
  - docker push giakoumis/multi-nginx
  - docker push giakoumis/multi-server
  - docker push giakoumis/multi-worker